story #8693 add tnr preservation
ProgrammeVitam/vitam-itests pull request #24
Opened 2021-10-28 08:51 UTC by mohatizaoui

2021-11-09 14:17 UTC, mascoun requested changes

2021-11-09 14:17 UTC, mascoun commented on preservation.feature
> +    Et je recherche le JCV du groupe d'objet de l'unité archivistique dont le titre est Gallieni par producteur1
il manque quelque chose là non ?
`Alors  Le fichier binaire du type du qualifier BinaryMaster n'a pas été généré`
ou 
`Alors  le type du binaire généré est un BinaryMaster et de type image/gif`

2021-11-10 09:57 UTC, GhrabSaifEddine approved these changes

2021-11-15 08:16 UTC, GhrabSaifEddine approved these changes

2021-11-15 08:49 UTC, mascoun approved these changes

2021-11-15 08:52 UTC, merged